const mockProducts = [
  {
    id: 'demo-hoodie',
    name: 'Classic Denim Hoodie',
    slug: 'classic-denim-hoodie',
    description: 'A comfortable everyday hoodie for casual style.',
    price: 1800,
    sale_price: 1499,
    currency: 'KES',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
    image_urls: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'],
    vendor_name: 'Dennis Mendez Studio',
    vendor_slug: 'dennis-mendez-studio',
    category_slug: 'fashion',
    free_shipping: true,
    weight: 0.45,
    length: 25,
    width: 20,
    height: 5,
  },
  {
    id: 'demo-bag',
    name: 'Leather Travel Bag',
    slug: 'leather-travel-bag',
    description: 'A durable travel companion with premium finish.',
    price: 3200,
    sale_price: 2799,
    currency: 'KES',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    image_urls: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'],
    vendor_name: 'East Africa Market',
    vendor_slug: 'east-africa-market',
    category_slug: 'accessories',
    free_shipping: true,
    weight: 1.2,
    length: 40,
    width: 25,
    height: 15,
  },
  {
    id: 'demo-shoe',
    name: 'Urban Runner Shoes',
    slug: 'urban-runner-shoes',
    description: 'Lightweight running shoes with all-day comfort.',
    price: 2600,
    sale_price: 2200,
    currency: 'KES',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    image_urls: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'],
    vendor_name: 'Urban Goods',
    vendor_slug: 'urban-goods',
    category_slug: 'footwear',
    free_shipping: false,
    weight: 0.7,
    length: 28,
    width: 16,
    height: 10,
  },
  {
    id: 'demo-watch',
    name: 'Minimalist Wrist Watch',
    slug: 'minimalist-wrist-watch',
    description: 'An elegant everyday watch with a slim profile.',
    price: 4500,
    sale_price: 3999,
    currency: 'KES',
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
    image_urls: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80'],
    vendor_name: 'Timeless Goods',
    vendor_slug: 'timeless-goods',
    category_slug: 'accessories',
    free_shipping: true,
    weight: 0.2,
    length: 12,
    width: 3,
    height: 2,
  },
];

const mockCategories = [
  { id: 'fashion', name: 'Fashion', slug: 'fashion', description: 'Style essentials', image_url: '' },
  { id: 'accessories', name: 'Accessories', slug: 'accessories', description: 'Useful add-ons', image_url: '' },
  { id: 'footwear', name: 'Footwear', slug: 'footwear', description: 'Comfort and movement', image_url: '' },
];

const mockStores = [
  { id: 'dennis-mendez-studio', slug: 'dennis-mendez-studio', business_name: 'Dennis Mendez Studio', logo_url: '', banner_url: '', business_type: 'fashion', description: 'Curated style pieces', city: 'Nairobi', country: 'Kenya' },
  { id: 'east-africa-market', slug: 'east-africa-market', business_name: 'East Africa Market', logo_url: '', banner_url: '', business_type: 'retail', description: 'Everyday essentials', city: 'Kampala', country: 'Uganda' },
  { id: 'urban-goods', slug: 'urban-goods', business_name: 'Urban Goods', logo_url: '', banner_url: '', business_type: 'footwear', description: 'Active lifestyle items', city: 'Dar es Salaam', country: 'Tanzania' },
];

export function getMockCatalog() {
  return {
    products: mockProducts,
    categories: mockCategories,
    stores: mockStores,
  };
}
